# Skylake Lighting System: Moonraker connection to WLED.
# Change address and chain_count before installation.
[wled skylake_lights]
type: http
address: 192.168.0.123
initial_preset: 1
chain_count: 20
